### ISSUE TITLE
Some resources with accents are not correctly identified

### ISSUE THREAD

**Issue by albertmata** [Microsoft/RESX-Unused-Finder#1]
I have a resource whose name is "Epígrafe", that is used inside a .cs file. This resource is incorrectly identified as unused. I suspect it may have something to do with the way you read resources and files, ¿UTF8?

**Comment by RandomEngy** [comment]
The file with the resource reference in it: how is it encoded? I just tried referring to a resource named Epígrafe and it recognized it both in a .cs and .xaml file.

**Comment by albertmata** [comment]
The resx file is encoded using UTF-8. But the .cs file where this "epígrafe" resource is used is encoded in ANSI.

**Comment by RandomEngy** [comment]
Thanks. Should be fixed in the latest ClickOnce release.
